---
title: "Final Project"
author: "Kelsea MacDonald"
date: "2023-03-06"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#path <-  "~/Library/CloudStorage/OneDrive-UniversityofCalifornia,Davis/ESP106/esp106-kelsea_macdonald/final project"
#setwd(path)
```

```{r}
# Read in file:
# URL = "http://berkeleyearth.lbl.gov/auto/Regional/TMAX/Text/california-TMAX-Trend.txt"
# f = file.path("data", basename(URL))
# if (!file.exists(f)) {
#   dir.create("data", FALSE, FALSE)
#   download.file(URL, f, mode="wb")
# }
# This is the file for daily max land temperature anomaly from 1870 to 2019 in the state of California
# Data is split into monthly, annual, 5-year, 10-year, and 20-year anomalies
# Berkeley Earth
```
Downloading Temp Data for US:
```{r}
temp.URL = "http://berkeleyearth.lbl.gov/auto/Regional/TMAX/Text/united-states-TMAX-Trend.txt"
temp.file = file.path("data", basename(temp.URL))
if(!file.exists(temp.file)) {
  dir.create("data", FALSE, FALSE)
  download.file(temp.URL, temp.file, mode="wb")
}
```
Creating Matrix of Temp Data:
```{r}
r = read.delim(file = temp.file, skip = 67, header = FALSE)
t.hdr = r[1:2,]
t.data = r[-c(1:3),]
t.data = stringr::str_squish(t.data)
t.data = strsplit(t.data, " ")
t.data = do.call(rbind, t.data)
t.data = matrix(as.numeric(t.data), nrow=nrow(t.data))
colnames(t.data) <- c("Year", "Month", "Monthly Anomaly", "Monthly Anomaly Unc", 
                 "Annual Anomaly", "Annual Anomaly Unc", "Five-year Anomaly", 
                 "Five-year Anomaly Unc", "Ten-year Anomaly", "Ten-year Anomaly Unc",
                 "Twenty-year Anomaly", "Twenty-year Anomaly Unc")
t.data <- as.data.frame(t.data)
```

```{r, scratch} 
# Scratch work from when I was figuring things out:
#Delete before finishing:
# list.files(path)
# library(terra)
# dailyTMAX60 <- rast("Complete_TMAX_Daily_LatLong1_1960.nc")
# plot(dailyTMAX60)
# dailyTMAX60 is the average max land temperature from 1960 to 1969 for the whole world
## data <- data.frame(strsplit(data[1,1], split = ","), strsplit(data[2:1796,1], split = " "))
# data <- as.matrix(data, ncol=12)
# separate(data) #not working :/

# library(dplyr)
# library(tidyr)
# data <- read.delim(file="california-TMAX-Trend.txt", skip = 68, sep="\t", quote="", comment.char="")
# separate(data, col =1, sep=" ")f = "california-TMAX-Trend.txt"

```

temperature anomaly data for California:
```{r}
# Read txt file "f" with first 68 comment lines removed, readLines method
# x = readLines(f)
# x = x[-c(1:68)]
# 
# # read.delim method
# data <- read.delim(file= f, skip=68, header=F)
# # Then set header as the first 2 rows
# hdr = data[1:2,]
# set rest as the data
# d= data[-c(1:3),]
# # turn the multiple spaces into single spaces
# d = stringr::str_squish(d)
# # split the string into separate characters by single space
# y = strsplit(d, " ")
# # bind the strings into rows
# z = do.call(rbind, y)
# # binds the rows into a matrix and changes the variables to numeric
# z = matrix(as.numeric(z), nrow=nrow(z))
# head(z)
# colnames(z) <- c("Year", "Month", "Monthly Anomaly", "Monthly Anomaly Unc", 
#                  "Annual Anomaly", "Annual Anomaly Unc", "Five-year Anomaly", 
#                  "Five-year Anomaly Unc", "Ten-year Anomaly", "Ten-year Anomaly Unc",
#                  "Twenty-year Anomaly", "Twenty-year Anomaly Unc")
# a <- as.data.frame(z)
# colnames(a) <- c("Year", "Month", "Monthly Anomaly", "Monthly Anomaly Unc", 
#                  "Annual Anomaly", "Annual Anomaly Unc", "Five-year Anomaly", 
#                  "Five-year Anomaly Unc", "Ten-year Anomaly", "Ten-year Anomaly Unc",
#                  "Twenty-year Anomaly", "Twenty-year Anomaly Unc")
```

Dowloading bird data:
```{r}
# library(rjson)
# URL.bird = "	https://www.sciencebase.gov/MigrantNonBreeder.zip"
# f.bird = file.path("data", basename(URL.bird))
# if (!file.exists(f.bird)) {
#   download.file(URL.bird, f.bird, mode="wb")
# }

#Make this reproducible later
migrant.sum <- file.path(path, "data", "MigrantNonBreeder", "MigrantSummary.csv")
birds <- read.csv(migrant.sum)
```

Creating data.frame for lesser yellow legs in US:
```{r}
# AOU 2550 = lesser yellowlegs
yl <- subset(birds, AOU == 2550)
# 840 = US
us.yl <- subset(yl, CountryNum == 840)
# We have data for 1992 to 2021 so we need to subset our temp data
plot(us.yl$Year, us.yl$SpeciesTotal)
agg <- aggregate(SpeciesTotal ~ Year, data=us.yl, FUN=sum)

```

```{r}
temp <- subset(t.data, Year < 2021 & Year > 1990)
plot(temp$Year, temp$`Annual Anomaly`)
```

```{r}
merg <- merge(temp, agg, by = 'Year')
plot(merg$`Annual Anomaly`, merg$SpeciesTotal)
plot(merg$`Monthly Anomaly`, merg$SpeciesTotal)
```

